version: '2.2'

services:
  db:
    image: mysql:5.7
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: openmrs
      MYSQL_ROOT_PASSWORD: Admin123
    volumes:
      - ./:/docker-entrypoint-initdb.d

  web:
    depends_on:
      - db
    image: tomcat:7
    volumes:
      - ./openmrs.war:/usr/local/tomcat/webapps/openmrs.war
      - ./openmrs-runtime.properties:/root/.OpenMRS/openmrs-runtime.properties
    links:
      - db:openmrs
    ports:
      - '8080:8080'
    environment:
      MYSQL_ROOT_PASSWORD: Admin123
      MYSQL_DATABASE: openmrs