name: RefApp 3.x Login
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  repository_dispatch:
    types: [qa]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Checkout openmrs-distro-referenceapplication
        uses: actions/checkout@master
        with:
          repository: openmrs/openmrs-distro-referenceapplication
          ref: 3.x
      - name: Run Openmrs
        run: |
          mvn clean package
          cd run/docker
          docker-compose up -d
      - name: Checkout qaframework
        uses: actions/checkout@master
        with:
          repository: ${{github.repository}}
      - name: Wait for Openmrs instance to start
        run: while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost/openmrs/login.htm)" != "200" ]]; do sleep 1; done
      - name: Using Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Installing dependencies
        run: npm install
      - name: Test the proxy
        run: |
          curl http://localhost/openmrs/login.htm
          curl http://localhost/openmrs/spa/home  # test the frontend
      - name: Run patient login workflow tests
        run: npm run refApp3Login

